
undefined4 gendsa_main(int param_1,int param_2)

{
  bool bVar1;
  undefined *puVar2;
  undefined4 uVar3;
  int iVar4;
  byte **ppbVar5;
  undefined4 *puVar6;
  undefined4 uVar7;
  byte *pbVar8;
  byte *pbVar9;
  byte *pbVar10;
  undefined8 uVar11;
  undefined uStack_95;
  int iStack_94;
  undefined4 uStack_90;
  int iStack_8c;
  byte *pbStack_88;
  code *pcStack_84;
  int *local_70;
  undefined4 local_6c;
  int local_68;
  undefined *local_60;
  byte *local_54;
  int local_50;
  int *local_4c;
  byte *local_48;
  undefined *local_44;
  undefined4 local_40;
  char *local_3c;
  byte *local_38;
  uint local_34;
  int local_30;
  int local_2c;
  
  puVar2 = PTR_bio_err_006a7f3c;
  local_4c = (int *)PTR___stack_chk_guard_006aabf0;
  local_60 = &_gp;
  local_30 = 0;
  local_2c = *(int *)PTR___stack_chk_guard_006aabf0;
  (*(code *)PTR_signal_006aabe0)(0xd,1);
  iVar4 = *(int *)puVar2;
  if (iVar4 == 0) {
    uVar3 = (**(code **)(local_60 + -0x7f40))();
    iVar4 = (**(code **)(local_60 + -0x7f3c))(uVar3);
    *(int *)puVar2 = iVar4;
    if (iVar4 != 0) {
      (**(code **)(local_60 + -0x7fc8))(iVar4,0x6a,0x10,**(undefined4 **)(local_60 + -0x52e0));
      iVar4 = *(int *)puVar2;
    }
  }
  iVar4 = load_config(iVar4,0);
  if (iVar4 == 0) {
    iStack_8c = 0;
    pbStack_88 = (byte *)0x0;
    goto LAB_00440b6c;
  }
  param_1 = param_1 + -1;
  ppbVar5 = (byte **)(param_2 + 4);
  if (param_1 < 1) {
LAB_00440c08:
    iStack_8c = 0;
    pbStack_88 = (byte *)0x0;
    (**(code **)(local_60 + -0x7fa8))(*(undefined4 *)puVar2,"usage: gendsa [args] dsaparam-file\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2," -out file - output the key to \'file\'\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2," -des      - encrypt the generated key with DES in cbc mode\n"
              );
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,
               " -des3     - encrypt the generated key with DES in ede cbc mode (168 bit key)\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,
               " -idea     - encrypt the generated key with IDEA in cbc mode\n");
    (**(code **)(local_60 + -0x7fa8))(*(undefined4 *)puVar2," -seed\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,"                 encrypt PEM output with cbc seed\n");
    (**(code **)(local_60 + -0x7fa8))(*(undefined4 *)puVar2," -aes128, -aes192, -aes256\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,"                 encrypt PEM output with cbc aes\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2," -camellia128, -camellia192, -camellia256\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,"                 encrypt PEM output with cbc camellia\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2," -engine e - use engine e, possibly a hardware device.\n");
    (**(code **)(local_60 + -0x7fa8))(*(undefined4 *)puVar2," -rand file%cfile%c...\n",0x3a,0x3a);
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,
               "           - load the file (or the files in the directory) into\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,"             the random number generator\n");
    (**(code **)(local_60 + -0x7fa8))(*(undefined4 *)puVar2," dsaparam-file\n");
    (**(code **)(local_60 + -0x7fa8))
              (*(undefined4 *)puVar2,
               "           - a DSA parameter file as generated by the dsaparam command\n");
LAB_00440b6c:
    uStack_90 = 1;
    (**(code **)(local_60 + -0x7fa0))(*(undefined4 *)puVar2);
    if (iStack_8c != 0) goto LAB_00440b84;
  }
  else {
    local_54 = (byte *)0x0;
    local_40 = 0;
    local_38 = (byte *)0x0;
    local_50 = 0x630000;
    pbVar10 = (byte *)0x0;
    local_48 = (byte *)0x0;
    pbVar9 = (byte *)0x0;
    local_44 = &DAT_0063ad0c;
    local_3c = "s\n";
    do {
      while( true ) {
        pbVar8 = *ppbVar5;
        iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,&DAT_00632edc);
        if (iVar4 == 0) {
          param_1 = param_1 + -1;
          if (param_1 != 0) {
            pbVar9 = ppbVar5[1];
            ppbVar5 = ppbVar5 + 1;
            pbVar8 = local_38;
            goto LAB_00440a98;
          }
          goto LAB_00440c08;
        }
        iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-passout");
        if (iVar4 == 0) break;
        iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-engine");
        if (iVar4 == 0) {
          param_1 = param_1 + -1;
          if (param_1 == 0) goto LAB_00440c08;
          local_54 = ppbVar5[1];
          ppbVar5 = ppbVar5 + 1;
          pbVar8 = local_38;
LAB_00440a98:
          local_38 = pbVar8;
          param_1 = param_1 + -1;
        }
        else {
          iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,local_50 + 0x30fc);
          if (iVar4 == 0) {
            param_1 = param_1 + -1;
            if (param_1 != 0) {
              local_48 = ppbVar5[1];
              ppbVar5 = ppbVar5 + 1;
              pbVar8 = local_38;
              goto LAB_00440a98;
            }
            goto LAB_00440c08;
          }
          local_34 = (uint)*pbVar8;
          if ((local_34 == 0x2d) && (pbVar8[1] == 0)) goto LAB_00440c08;
          iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,local_44);
          if (iVar4 == 0) {
            param_1 = param_1 + -1;
            local_40 = (**(code **)(local_60 + -0x7b3c))();
          }
          else {
            iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,local_3c + -0x52ec);
            if (iVar4 == 0) {
              param_1 = param_1 + -1;
              local_40 = (**(code **)(local_60 + -0x7f98))();
            }
            else {
              iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-idea");
              if (iVar4 == 0) {
                param_1 = param_1 + -1;
                local_40 = (**(code **)(local_60 + -0x7b38))();
              }
              else {
                iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-seed");
                if (iVar4 == 0) {
                  param_1 = param_1 + -1;
                  local_40 = (**(code **)(local_60 + -0x7b28))();
                }
                else {
                  iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-aes128");
                  if (iVar4 == 0) {
                    param_1 = param_1 + -1;
                    local_40 = (**(code **)(local_60 + -0x7b2c))();
                  }
                  else {
                    iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-aes192");
                    if (iVar4 == 0) {
                      param_1 = param_1 + -1;
                      local_40 = (**(code **)(local_60 + -0x7b30))();
                    }
                    else {
                      iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-aes256");
                      if (iVar4 == 0) {
                        param_1 = param_1 + -1;
                        local_40 = (**(code **)(local_60 + -0x7b34))();
                      }
                      else {
                        iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-camellia128");
                        if (iVar4 == 0) {
                          param_1 = param_1 + -1;
                          local_40 = (**(code **)(local_60 + -0x7b20))();
                        }
                        else {
                          iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-camellia192");
                          if (iVar4 == 0) {
                            param_1 = param_1 + -1;
                            local_40 = (**(code **)(local_60 + -0x7b24))();
                          }
                          else {
                            iVar4 = (**(code **)(local_60 + -0x52c0))(pbVar8,"-camellia256");
                            if (iVar4 != 0) {
                              if ((local_34 != 0x2d) && (local_38 == (byte *)0x0))
                              goto LAB_00440a98;
                              goto LAB_00440c08;
                            }
                            param_1 = param_1 + -1;
                            local_40 = (**(code **)(local_60 + -0x7b1c))();
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        ppbVar5 = ppbVar5 + 1;
        if (param_1 == 0) goto LAB_00440af4;
      }
      bVar1 = param_1 == 1;
      param_1 = param_1 + -2;
      if (bVar1) goto LAB_00440c08;
      pbVar10 = ppbVar5[1];
      ppbVar5 = ppbVar5 + 2;
    } while (param_1 != 0);
LAB_00440af4:
    if (local_38 == (byte *)0x0) goto LAB_00440c08;
    puVar6 = *(undefined4 **)(local_60 + -0x7fa4);
    setup_engine(*(undefined4 *)puVar2,local_54,0);
    local_70 = &local_30;
    iVar4 = app_passwd(*(undefined4 *)puVar2,0,pbVar10,0);
    if (iVar4 == 0) {
      iStack_8c = 0;
      pbStack_88 = (byte *)0x0;
      (**(code **)(local_60 + -0x7fa8))(*puVar6,"Error getting password\n");
      goto LAB_00440b6c;
    }
    uVar3 = (**(code **)(local_60 + -0x7f40))();
    iStack_8c = (**(code **)(local_60 + -0x7f3c))(uVar3);
    pbStack_88 = local_38;
    iVar4 = (**(code **)(local_60 + -0x7fc8))(iStack_8c,0x6c,3,local_38);
    if (iVar4 == 0) {
      (**(code **)(local_60 + -0x5358))(pbStack_88);
LAB_00441210:
      (**(code **)(local_60 + -0x7fa0))(*(undefined4 *)puVar2);
      if (iStack_8c == 0) {
        uStack_90 = 1;
      }
      else {
        uStack_90 = 1;
        (**(code **)(local_60 + -0x7f70))(iStack_8c);
      }
      goto LAB_00440ba8;
    }
    pbStack_88 = (byte *)(**(code **)(local_60 + -0x78ac))(iStack_8c,0,0,0);
    if (pbStack_88 == (byte *)0x0) {
      (**(code **)(local_60 + -0x7fa8))(*puVar6,"unable to load DSA parameter file\n");
      goto LAB_00441210;
    }
    (**(code **)(local_60 + -0x7f70))(iStack_8c);
    uVar3 = (**(code **)(local_60 + -0x7f40))();
    iStack_8c = (**(code **)(local_60 + -0x7f3c))(uVar3);
    if (iStack_8c == 0) goto LAB_00440b6c;
    if (pbVar9 == (byte *)0x0) {
      (**(code **)(local_60 + -0x7fc8))(iStack_8c,0x6a,0,**(undefined4 **)(local_60 + -0x540c));
    }
    else {
      iVar4 = (**(code **)(local_60 + -0x7fc8))(iStack_8c,0x6c,5,pbVar9);
      if (iVar4 < 1) {
        (**(code **)(local_60 + -0x5358))(pbVar9);
        goto LAB_00440b6c;
      }
    }
    iVar4 = app_RAND_load_file(0,*(undefined4 *)puVar2,1);
    if (iVar4 == 0) {
      if (local_48 == (byte *)0x0) {
        (**(code **)(local_60 + -0x7fa8))
                  (**(undefined4 **)(local_60 + -0x7fa4),
                   "warning, not much extra random data, consider using the -rand option\n");
      }
      else {
LAB_004410d8:
        uVar7 = *(undefined4 *)puVar2;
        uVar3 = app_RAND_load_files(local_48);
        (**(code **)(local_60 + -0x7fa8))(uVar7,"%ld semi-random bytes loaded\n",uVar3);
      }
    }
    else if (local_48 != (byte *)0x0) goto LAB_004410d8;
    uVar7 = *(undefined4 *)puVar2;
    uVar3 = (**(code **)(local_60 + -0x7bec))(*(undefined4 *)(pbStack_88 + 0xc));
    (**(code **)(local_60 + -0x7fa8))(uVar7,"Generating DSA key, %d bits\n",uVar3);
    iVar4 = (**(code **)(local_60 + -0x7774))(pbStack_88);
    if (iVar4 == 0) goto LAB_00440b6c;
    app_RAND_write_file(0,**(undefined4 **)(local_60 + -0x7fa4));
    local_6c = 0;
    local_70 = (int *)0x0;
    local_68 = local_30;
    iVar4 = (**(code **)(local_60 + -0x7780))(iStack_8c,pbStack_88,local_40,0);
    if (iVar4 == 0) goto LAB_00440b6c;
    uStack_90 = 0;
LAB_00440b84:
    (**(code **)(local_60 + -0x7f6c))(iStack_8c);
  }
  if (pbStack_88 != (byte *)0x0) {
    (**(code **)(local_60 + -0x78b4))(pbStack_88);
  }
LAB_00440ba8:
  if (local_30 != 0) {
    (**(code **)(local_60 + -0x7f58))();
  }
  if (local_2c != *local_4c) {
    pcStack_84 = genpkey_cb;
    iVar4 = local_2c;
    (**(code **)(local_60 + -0x5328))();
    puVar2 = PTR___stack_chk_guard_006aabf0;
    uStack_95 = 0x2a;
    iStack_94 = *(int *)PTR___stack_chk_guard_006aabf0;
    uVar3 = (*(code *)PTR_EVP_PKEY_CTX_get_app_data_006a7f0c)();
    iVar4 = (*(code *)PTR_EVP_PKEY_CTX_get_keygen_info_006a7f10)(iVar4,0);
    if (iVar4 == 0) {
      uStack_95 = 0x2e;
    }
    else if (iVar4 == 1) {
      uStack_95 = 0x2b;
    }
    else {
      uVar11 = CONCAT44(iVar4,3);
      if (iVar4 != 2) goto LAB_0044145c;
      uStack_95 = 0x2a;
    }
    while( true ) {
      (*(code *)PTR_BIO_write_006a7f14)(uVar3,&uStack_95,1);
      (*(code *)PTR_BIO_ctrl_006a7f18)(uVar3,0xb,0,0);
      if (iStack_94 == *(int *)puVar2) break;
      uVar11 = (*(code *)PTR___stack_chk_fail_006aabb8)();
LAB_0044145c:
      if ((int)((ulonglong)uVar11 >> 0x20) == (int)uVar11) {
        uStack_95 = 10;
      }
    }
    return 1;
  }
  return uStack_90;
}

