
PROXY_CERT_INFO_EXTENSION *
d2i_PROXY_CERT_INFO_EXTENSION(PROXY_CERT_INFO_EXTENSION **a,uchar **in,long len)

{
  PROXY_CERT_INFO_EXTENSION *pPVar1;
  
  pPVar1 = (PROXY_CERT_INFO_EXTENSION *)
           ASN1_item_d2i((ASN1_VALUE **)a,in,len,
                         (ASN1_ITEM *)PTR_PROXY_CERT_INFO_EXTENSION_it_000d8240);
  return pPVar1;
}

