
CERTIFICATEPOLICIES * d2i_CERTIFICATEPOLICIES(CERTIFICATEPOLICIES **a,uchar **in,long len)

{
  CERTIFICATEPOLICIES *pCVar1;
  
  pCVar1 = (CERTIFICATEPOLICIES *)
           ASN1_item_d2i((ASN1_VALUE **)a,in,len,(ASN1_ITEM *)PTR_CERTIFICATEPOLICIES_it_000d57fc);
  return pCVar1;
}

